### ISSUE TITLE
Error 403: access_denied

### ISSUE THREAD

**Issue by derekantrican** [jneilliii/OctoPrint-GoogleDriveBackup#14]
I followed the steps in the readme, but this is the screen is see when clicking on the link in the plugin to authorize:

![](https://i.imgur.com/ATSdIpJ.png)

Did I miss something?

**Comment by jneilliii** [comment]
I think this has to do with the scope. I'll have to go back and look at what's being used. Some dev stuff requires to be submitted for approval, just not sure if I had done that or not.

**Comment by derekantrican** [comment]
Personally don't agree with the idea of stalebot - an issue should be an issue until it's closed (whether that be as 'resolved' or as 'won't fix')

**Comment by jneilliii** [comment]
Yeah, sorry about that. Didn't label the issue appropriately. Too many times I have issues sit indefinitely because no one responds when I request for additional info, etc.

**Comment by jneilliii** [comment]
After walking through the process it seems something has changed a little from when I created the instructions, or I published the app from the get go. In any case, if you go to your apps OAuth consent screen settings and under test users add your email address you're trying to authorize that should allow you to go through the process. The reason seems to be because the app is in "testing" publishing status it means you have to have users defined to allow access. I'll update the instructions accordingly.

![image](https://user-images.githubusercontent.com/5249455/103146263-b2d2a780-4714-11eb-90cc-925fb984c460.png)

**Comment by derekantrican** [comment]
Can confirm - that seemed to work. Thanks!

**Comment by jneilliii** [comment]
Great, I've already added that step to the docs. Thanks for pointing it out and verifying.
