### ISSUE TITLE
[FR]: Improve Gdrive Registration Flow

### ISSUE THREAD

**Issue by poldim** [jneilliii/OctoPrint-GoogleDriveBackup#6]
**Is your feature request related to a problem? Please describe.**

Gdrive authentication flow seems unnecessarily complex

**Describe the solution you'd like**

Look at the solution implemented by https://github.com/sabeechen/hassio-google-drive-backup

**Describe alternatives you've considered**

**Additional context**

**Comment by jneilliii** [comment]
Yeah, I don't want to authorize an app with Google that gives me access to anyone else's Google Drive data, which in essence is what this addon is doing. They even mention that you can go the route of authorizing your own client id, etc. in their readme [here](https://github.com/sabeechen/hassio-google-drive-backup#can-i-use-my-own-google-api-information-to-authenticate-instead-of-yours). This is all an assumption though since I don't have access to HA at the moment.

**Comment by jneilliii** [comment]
It also appears that this plugin is running its own server as well?
